version: '3.0'
services:
    mvn-app:
       image: mohey/demo-app:${IMAGE_VERSION}
       ports: 
         - 8080:8080

    db:
      image: postgres:13
      ports: 
        - 5432:5432
      environment: 
        - POSTGRES_PASSWORD=mypassword
      

