---
- hosts: all
  name: Install Python3, Docker And Docker Compose
  become: yes
  tasks: 
    - name: Install Python3 And Docker 
      vars:
        - ansible_python_interpreter: /usr/bin/python
      yum:  
        name:
         - python3 
         - docker
        state: present 
        update_cache: yes
    - name: Install Docker Compose 
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-{{lookup('pipe','uname -m')}}"
        dest: "/usr/local/bin/docker-compose"
        mode: +x

    - name: Start Docker Daemon
      systemd:
        name: docker
        state: started
    - name: Install Docker and docker compose python modules
      pip:
       name:
        - docker
        - docker-compose
